name: tests

on:
  push:
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: pep8
        run: |
          tox -e pep8
  tests:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.10", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install libev-dev -y
      - name: Install tox
        run: pip install tox
      - name: Unit tests
        run: |
          tox -e ${{ matrix.python-version }}
      - name: Functional tests
        run: |
          tox -e ${{ matrix.python-version }}-functional
